name: kondo
description: A strict, feature-oriented architecture pattern for Flutter, enforcing pure decoupled logic and side-effect safety.
version: 0.0.2
homepage: https://github.com/parsodyl/kondo
repository: https://github.com/parsodyl/kondo
issue_tracker: https://github.com/parsodyl/kondo/issues

topics:
  - architecture
  - state-management
  - clean-architecture
  - mvi

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  collection: ^1.17.0
  hako: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
